# Generated by Django 4.0.6 on 2022-07-28 22:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=14, null=True)),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=240)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoseAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
            ],
        ),
        migrations.CreateModel(
            name='RoseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.roseamount')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rosecolor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('surname', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('PICKUP', 'PICKUP'), ('DELIVERY', 'DELIVERY')], default='PICKUP', max_length=100)),
                ('status', models.CharField(choices=[('In process', 'In process'), ('Packed', 'Packed'), ('Delivering', 'Delivering'), ('Done', 'Done')], default='In process', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('amount', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.roseamount')),
                ('color', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='main.rosecolor')),
                ('color2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='main.rosecolor')),
                ('color3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='main.rosecolor')),
            ],
        ),
    ]
