# Generated by Django 4.0.6 on 2022-07-28 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rosecolor_remove_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rosecolor'),
        ),
    ]
