# Generated by Django 4.0.6 on 2022-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoseAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
