# Generated by Django 4.0.6 on 2022-07-28 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roseamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roseamount',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
