# Generated by Django 4.0.6 on 2022-07-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_order_product_order_amount_order_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='main.rosecolor'),
        ),
        migrations.AddField(
            model_name='order',
            name='color3',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='main.rosecolor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='main.rosecolor'),
        ),
    ]
