# Generated by Django 4.0.6 on 2022-07-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_color2_order_color3_alter_order_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='main.rosecolor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='main.rosecolor'),
        ),
    ]
