# Generated by Django 4.0.6 on 2022-07-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_order_color2_alter_order_color3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
