# Generated by Django 4.0.6 on 2022-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In process', 'In process'), ('Packed', 'Packed'), ('Delivering', 'Delivering'), ('Done', 'Done')], default='In process', max_length=100),
        ),
    ]
